name: Ridout Headshots
favicon: null
layout_spectrum: 0.7443491071462631
typography_spectrum: 0.4521039607934654
title: Making People Beautiful One Click At A Time
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4794646054506302
  lightness: 0.3291511267889291
  saturation: 0.6430127986241132
  rhythmicContrast: 0.7289209510199726
purpose: []
